stages:
  - build
  - test
  - deploy

variables:
  DJANGO_SETTINGS_MODULE: vidixer.settings
  DATABASE_URL: postgres://postgres:postgres@db:5432/vidixer

build-backend:
  stage: build
  image: python:latest
  before_script:
    - python -V
    - pip install --upgrade pip
  script:
    - echo "[ Build ] installing required libraries from requirements.txt ..."
    - pip install -r backend/requirements.txt
    - python3 backend/manage.py makemigrations
    # - python3 manage.py makemigrations myapp
    - python3 backend/manage.py migrate
    - python3 backend/manage.py check

build-frontend:
  stage: build
  image: node:latest
  script:
    - echo "[ [ Build ] Going in frontend"
    - cd frontend
    - echo "[ [ Build ] installing npm packages ..."
    - npm install
    - echo "[ [ Build ] running the build ..."
    - npm run build
  artifacts:
    paths:
      - frontend/dist
    expire_in: 1 hour
  only:
    refs:
      - main
      - develop

test-backend:
  stage: test
  image: python:latest
  script:
    - echo "[ test ] installing required libraries from requirements.txt ..."
    - pip install -r backend/requirements.txt
    - echo "[ test ] Testing Backend server ..."
    - python backend/manage.py test

# deploy:
#   stage: deploy
#   script:
#     - echo "Deploy step goes here"
