# Generated by Django 5.2.3 on 2025-06-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('needs_review', 'Needs Review'), ('completed', 'Completed')], default='submitted', max_length=20)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/raw/')),
                ('draft_video', models.FileField(blank=True, null=True, upload_to='uploads/drafts/')),
                ('final_video', models.FileField(blank=True, null=True, upload_to='uploads/final/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
