# Generated by Django 5.0.3 on 2024-04-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidixerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='mideas/videos/'),
        ),
    ]
