# Generated by Django 5.0.3 on 2024-04-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidixerapp', '0003_alter_video_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='average_rating',
        ),
    ]
