# Generated by Django 5.0.3 on 2024-06-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidixerapp', '0012_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='media/videos/'),
        ),
    ]
